version: '3.4'
services:
  MFI_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MFI_TrailingStopMethod
      RUN_ON_SET: set_opt_params MFI_TrailingStopMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-MFI_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-MFI_TrailingStopMethod
    deploy:
      restart_policy:
        condition: none
  MFI_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MFI_TrailingProfitMethod
      RUN_ON_SET: set_opt_params MFI_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-MFI_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-MFI_TrailingProfitMethod
    deploy:
      restart_policy:
        condition: none
