---
version: '3.4'
services:
  Alligator1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator1_SignalMethod
      RUN_ON_SET: set_opt_params Alligator1_SignalMethod -31 31
      SETFILE: /opt/sets/EA31337-Alligator1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Alligator1_SignalMethod
  Alligator5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator5_SignalMethod
      RUN_ON_SET: set_opt_params Alligator5_SignalMethod -31 31
      SETFILE: /opt/sets/EA31337-Alligator5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Alligator5_SignalMethod
  Alligator15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator15_SignalMethod
      RUN_ON_SET: set_opt_params Alligator15_SignalMethod -31 31
      SETFILE: /opt/sets/EA31337-Alligator15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Alligator15_SignalMethod
  Alligator30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator30_SignalMethod
      RUN_ON_SET: set_opt_params Alligator30_SignalMethod -31 31
      SETFILE: /opt/sets/EA31337-Alligator30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Alligator30_SignalMethod
