---
version: '3.4'
services:
  ADX1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params ADX1_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-ADX1_SignalMethod.set
      SET_PARAMS: ADX1_SignalMethod
      TEST_REPORT_NAME: EA31337-ADX1_SignalMethod
  ADX5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params ADX5_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-ADX5_SignalMethod.set
      SET_PARAMS: ADX5_SignalMethod
      TEST_REPORT_NAME: EA31337-ADX5_SignalMethod
  ADX15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params ADX15_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-ADX15_SignalMethod.set
      SET_PARAMS: ADX15_SignalMethod
      TEST_REPORT_NAME: EA31337-ADX15_SignalMethod
  ADX30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params ADX30_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-ADX30_SignalMethod.set
      SET_PARAMS: ADX30_SignalMethod
      TEST_REPORT_NAME: EA31337-ADX30_SignalMethod
