---
version: '3.4'
services:
  Force_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: set_opt_params Force_TrailingStopMethod 1 -25 0
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Force_TrailingProfitMethod.set
      SETFILE: /opt/sets/EA31337-Force_TrailingStopMethod.set
      SET_PARAMS: Force_TrailingStopMethod
      TEST_REPORT_NAME: EA31337-Force_TrailingStopMethod
  Force_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: set_opt_params Force_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-Force_TrailingProfitMethod.set
      SET_PARAMS: Force_TrailingProfitMethod
      TEST_REPORT_NAME: EA31337-Force_TrailingProfitMethod
