version: '3.4'
services:
  RSI_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI1_Active,RSI5_Active,RSI15_Active,RSI30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI_Active.set
      TEST_REPORT_NAME: EA31337-RSI_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  RSI1_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI1_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI1_Active.set
      TEST_REPORT_NAME: EA31337-RSI1_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  RSI5_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI5_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI5_Active.set
      TEST_REPORT_NAME: EA31337-RSI5_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  RSI15_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI15_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI15_Active.set
      TEST_REPORT_NAME: EA31337-RSI15_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  RSI30_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-RSI30_Active.set
      TEST_REPORT_NAME: EA31337-RSI30_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
