---
version: '3.4'
services:
  Envelopes_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SET_PARAMS: Envelopes_TrailingStopMethod
      RUN_ON_SET: set_opt_params Envelopes_TrailingStopMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-Envelopes_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes_TrailingStopMethod
  Envelopes_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SET_PARAMS: Envelopes_TrailingProfitMethod
      RUN_ON_SET: set_opt_params Envelopes_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-Envelopes_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes_TrailingProfitMethod
