version: '3.4'
services:
  SAR1_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR1_Active
      SETFILE: /opt/sets/EA31337-SAR1_Active.set
      TEST_REPORT_NAME: EA31337-SAR1_Active
    deploy:
      restart_policy:
        condition: none
  SAR5_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR5_Active
      SETFILE: /opt/sets/EA31337-SAR5_Active.set
      TEST_REPORT_NAME: EA31337-SAR5_Active
    deploy:
      restart_policy:
        condition: none
  SAR15_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR15_Active
      SETFILE: /opt/sets/EA31337-SAR15_Active.set
      TEST_REPORT_NAME: EA31337-SAR15_Active
    deploy:
      restart_policy:
        condition: none
  SAR30_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR30_Active
      SETFILE: /opt/sets/EA31337-SAR30_Active.set
      TEST_REPORT_NAME: EA31337-SAR30_Active
    deploy:
      restart_policy:
        condition: none
