---
version: '3.4'
services:
  AD1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params AD1_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AD1_SignalMethod.set
      SET_PARAMS: AD1_SignalMethod
      TEST_REPORT_NAME: EA31337-AD1_SignalMethod
  AD5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params AD5_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AD5_SignalMethod.set
      SET_PARAMS: AD5_SignalMethod
      TEST_REPORT_NAME: EA31337-AD5_SignalMethod
  AD15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params AD15_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AD15_SignalMethod.set
      SET_PARAMS: AD15_SignalMethod
      TEST_REPORT_NAME: EA31337-AD15_SignalMethod
  AD30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=10
      RUN_ON_SET: set_opt_params AD30_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AD30_SignalMethod.set
      SET_PARAMS: AD30_SignalMethod
      TEST_REPORT_NAME: EA31337-AD30_SignalMethod
