---
version: '3.4'
services:
  ADX_Period_M1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params ADX_Period_M1
        $$(get_max 2 $$(bc <<< "$$(input_get ADX_Period_M1) - 2 * 4"))
        $$(bc <<< "$$(input_get ADX_Period_M1) + 2 * 4")
        2
      SET_PARAMS: ADX_Period_M1
      SETFILE: /opt/sets/EA31337-ADX_Period_M1.set
      TEST_REPORT_NAME: EA31337-ADX_Period_M1
  ADX_Period_M5:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params ADX_Period_M5
        $$(get_max 2 $$(bc <<< "$$(input_get ADX_Period_M5) - 2 * 4"))
        $$(bc <<< "$$(input_get ADX_Period_M5) + 2 * 4")
        2
      SET_PARAMS: ADX_Period_M5
      SETFILE: /opt/sets/EA31337-ADX_Period_M5.set
      TEST_REPORT_NAME: EA31337-ADX_Period_M5
  ADX_Period_M15:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params ADX_Period_M15
        $$(get_max 2 $$(bc <<< "$$(input_get ADX_Period_M15) - 2 * 4"))
        $$(bc <<< "$$(input_get ADX_Period_M15) + 2 * 4")
        2
      SET_PARAMS: ADX_Period_M15
      SETFILE: /opt/sets/EA31337-ADX_Period_M15.set
      TEST_REPORT_NAME: EA31337-ADX_Period_M15
  ADX_Period_M30:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params ADX_Period_M30
        $$(get_max 2 $$(bc <<< "$$(input_get ADX_Period_M30) - 2 * 4"))
        $$(bc <<< "$$(input_get ADX_Period_M30) + 2 * 4")
        2
      SET_PARAMS: ADX_Period_M30
      SETFILE: /opt/sets/EA31337-ADX_Period_M30.set
      TEST_REPORT_NAME: EA31337-ADX_Period_M30
  ADX_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: set_opt_params ADX_Applied_Price 0 6
      SETFILE: /opt/sets/EA31337-ADX_Applied_Price.set
      SET_PARAMS: ADX_Applied_Price
      TEST_REPORT_NAME: EA31337-ADX_Applied_Price
  ADX_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params ADX_SignalLevel
        $$(bc <<< "$$(input_get ADX_SignalLevel) - 0.1 * 5")
        $$(bc <<< "$$(input_get ADX_SignalLevel) + 0.1 * 5")
        0.1
      SETFILE: /opt/sets/EA31337-ADX_SignalLevel.set
      SET_PARAMS: ADX_SignalLevel
      TEST_REPORT_NAME: EA31337-ADX_SignalLevel
  ADX_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params ADX_Shift
        $$(bc <<< "$$(input_get ADX_Shift) - 1 * 2")
        $$(bc <<< "$$(input_get ADX_Shift) + 1 * 2")
      SETFILE: /opt/sets/EA31337-ADX_Shift.set
      SET_PARAMS: ADX_Shift
      TEST_REPORT_NAME: EA31337-ADX_Shift
