---
version: '3.4'
services:
  MA1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SETFILE: /opt/sets/EA31337-MA1_SignalMethod.set
      SET_PARAMS: MA1_SignalMethod
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      TEST_REPORT_NAME: EA31337-MA1_SignalMethod
  MA5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SETFILE: /opt/sets/EA31337-MA5_SignalMethod.set
      SET_PARAMS: MA5_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      TEST_REPORT_NAME: EA31337-MA5_SignalMethod
  MA15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SETFILE: /opt/sets/EA31337-MA15_SignalMethod.set
      SET_PARAMS: MA15_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      TEST_REPORT_NAME: EA31337-MA15_SignalMethod
  MA30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SETFILE: /opt/sets/EA31337-MA30_SignalMethod.set
      SET_PARAMS: MA30_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      TEST_REPORT_NAME: EA31337-MA30_SignalMethod
