---
version: '3.4'
services:
  SAR1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR1_SignalMethod
      RUN_ON_SET: set_opt_params SAR1_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-SAR1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-SAR1_SignalMethod
  SAR5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR5_SignalMethod
      RUN_ON_SET: set_opt_params SAR5_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-SAR5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-SAR5_SignalMethod
  SAR15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR15_SignalMethod
      RUN_ON_SET: set_opt_params SAR15_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-SAR15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-SAR15_SignalMethod
  SAR30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR30_SignalMethod
      RUN_ON_SET: set_opt_params SAR30_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-SAR30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-SAR30_SignalMethod
