---
version: '3.4'
services:
  SAR1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 5"))
        7
      SETFILE: /opt/sets/EA31337-SAR1_SignalMethod.set
      SET_PARAMS: SAR1_SignalMethod
      TEST_REPORT_NAME: EA31337-SAR1_SignalMethod
  SAR5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 5"))
        7
      SETFILE: /opt/sets/EA31337-SAR5_SignalMethod.set
      SET_PARAMS: SAR5_SignalMethod
      TEST_REPORT_NAME: EA31337-SAR5_SignalMethod
  SAR15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 5"))
        7
      SETFILE: /opt/sets/EA31337-SAR15_SignalMethod.set
      SET_PARAMS: SAR15_SignalMethod
      TEST_REPORT_NAME: EA31337-SAR15_SignalMethod
  SAR30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 5"))
        7
      SETFILE: /opt/sets/EA31337-SAR30_SignalMethod.set
      SET_PARAMS: SAR30_SignalMethod
      TEST_REPORT_NAME: EA31337-SAR30_SignalMethod
