---
version: '3.4'
services:
  MACD_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=8
      RUN_ON_SET: set_opt_params MACD_TrailingStopMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-MACD_TrailingStopMethod.set
      SET_PARAMS: MACD_TrailingStopMethod
      TEST_REPORT_NAME: EA31337-MACD_TrailingStopMethod
  MACD_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=8
      RUN_ON_SET: set_opt_params MACD_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-MACD_TrailingProfitMethod.set
      SET_PARAMS: MACD_TrailingProfitMethod
      TEST_REPORT_NAME: EA31337-MACD_TrailingProfitMethod
