version: '3.4'
services:
  WPR_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR1_Active,WPR5_Active,WPR15_Active,WPR30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR_Active.set
      TEST_REPORT_NAME: EA31337-WPR_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  WPR1_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR1_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR1_Active.set
      TEST_REPORT_NAME: EA31337-WPR1_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  WPR5_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR5_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR5_Active.set
      TEST_REPORT_NAME: EA31337-WPR5_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  WPR15_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR15_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR15_Active.set
      TEST_REPORT_NAME: EA31337-WPR15_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
  WPR30_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR30_Active
      SETFILE: /opt/sets/EURUSD/EA31337-WPR30_Active.set
      TEST_REPORT_NAME: EA31337-WPR30_Active
      BT_DEST: /opt/_results/EURUSD
    deploy:
      restart_policy:
        condition: none
