version: '3.4'
services:
  Fractals_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Fractals1_Active,Fractals5_Active,Fractals15_Active,Fractals30_Active
      SETFILE: /opt/sets/EA31337-Fractals_Active.set
      TEST_REPORT_NAME: EA31337-Fractals_Active
    deploy:
      restart_policy:
        condition: none
