---
version: '3.4'
services:
  MFI1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MFI1_SignalMethod
      RUN_ON_SET: set_opt_params MFI1_SignalMethod -1 1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-MFI1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-MFI1_SignalMethod
  MFI5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MFI5_SignalMethod
      RUN_ON_SET: set_opt_params MFI5_SignalMethod -1 1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-MFI5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-MFI5_SignalMethod
  MFI15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MFI15_SignalMethod
      RUN_ON_SET: set_opt_params MFI15_SignalMethod -1 1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-MFI15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-MFI15_SignalMethod
  MFI30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MFI30_SignalMethod
      RUN_ON_SET: set_opt_params MFI30_SignalMethod -1 1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=50
      SETFILE: /opt/sets/EA31337-MFI30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-MFI30_SignalMethod
