---
version: '3.4'
services:
  CCI_Period_M1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: >
        set_opt_params CCI_Period_M1
        $$(get_max 3 $$(bc <<< "$$(input_get CCI_Period_M1) - 2 * 8"))
        $$(get_min 50 $$(bc <<< "$$(input_get CCI_Period_M1) + 2 * 8"))
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-CCI_Applied_Price.set
        /opt/sets/EA31337-CCI_Shift.set
        /opt/sets/EA31337-CCI_SignalLevel.set
      SETFILE: /opt/sets/EA31337-CCI_Period_M1.set
      SET_PARAMS: CCI_Period_M1
      TEST_REPORT_NAME: EA31337-CCI_Period_M1
  CCI_Period_M5:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET:
        set_opt_params CCI_Period_M5
        $$(get_max 3 $$(bc <<< "$$(input_get CCI_Period_M5) - 2 * 4"))
        $$(bc <<< "$$(input_get CCI_Period_M5) + 2 * 4")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-CCI_Applied_Price.set
        /opt/sets/EA31337-CCI_Shift.set
        /opt/sets/EA31337-CCI_SignalLevel.set
      SETFILE: /opt/sets/EA31337-CCI_Period_M5.set
      SET_PARAMS: CCI_Period_M5
      TEST_REPORT_NAME: EA31337-CCI_Period_M5
  CCI_Period_M15:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: >
        set_opt_params CCI_Period_M15
        $$(get_max 3 $$(bc <<< "$$(input_get CCI_Period_M15) - 2 * 4"))
        $$(bc <<< "$$(input_get CCI_Period_M15) + 2 * 4")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-CCI_Applied_Price.set
        /opt/sets/EA31337-CCI_Shift.set
        /opt/sets/EA31337-CCI_SignalLevel.set
      SETFILE: /opt/sets/EA31337-CCI_Period_M15.set
      SET_PARAMS: CCI_Period_M15
      TEST_REPORT_NAME: EA31337-CCI_Period_M15
  CCI_Period_M30:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: >
        set_opt_params CCI_Period_M30
        $$(get_max 3 $$(bc <<< "$$(input_get CCI_Period_M30) - 2 * 4"))
        $$(bc <<< "$$(input_get CCI_Period_M30) + 2 * 4")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-CCI_Applied_Price.set
        /opt/sets/EA31337-CCI_Shift.set
        /opt/sets/EA31337-CCI_SignalLevel.set
      SETFILE: /opt/sets/EA31337-CCI_Period_M30.set
      SET_PARAMS: CCI_Period_M30
      TEST_REPORT_NAME: EA31337-CCI_Period_M30
  CCI_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: set_opt_params CCI_Applied_Price 0 6
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-CCI_Period_M1.set
        /opt/sets/EA31337-CCI_Period_M5.set
        /opt/sets/EA31337-CCI_Period_M15.set
        /opt/sets/EA31337-CCI_Period_M30.set
        /opt/sets/EA31337-CCI_Shift.set
        /opt/sets/EA31337-CCI_SignalLevel.set
      SETFILE: /opt/sets/EA31337-CCI_Applied_Price.set
      SET_PARAMS: CCI_Applied_Price
      TEST_REPORT_NAME: EA31337-CCI_Applied_Price
  CCI_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: >
        set_opt_params CCI_SignalLevel
        $$(bc <<< "$$(input_get CCI_SignalLevel) - 1 * 8")
        $$(bc <<< "$$(input_get CCI_SignalLevel) + 1 * 8")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-CCI_Applied_Price.set
        /opt/sets/EA31337-CCI_Period_M1.set
        /opt/sets/EA31337-CCI_Period_M5.set
        /opt/sets/EA31337-CCI_Period_M15.set
        /opt/sets/EA31337-CCI_Period_M30.set
        /opt/sets/EA31337-CCI_Shift.set
      SETFILE: /opt/sets/EA31337-CCI_SignalLevel.set
      SET_PARAMS: CCI_SignalLevel
      TEST_REPORT_NAME: EA31337-CCI_SignalLevel
  CCI_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: >
        set_opt_params CCI_Shift
        $$(get_max 0 $$(bc <<< "$$(input_get CCI_Shift) - 1 * 2"))
        $$(bc <<< "$$(input_get CCI_Shift) + 1 * 2")
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-CCI_Applied_Price.set
        /opt/sets/EA31337-CCI_Period_M1.set
        /opt/sets/EA31337-CCI_Period_M5.set
        /opt/sets/EA31337-CCI_Period_M15.set
        /opt/sets/EA31337-CCI_Period_M30.set
        /opt/sets/EA31337-CCI_SignalLevel.set
      SETFILE: /opt/sets/EA31337-CCI_Shift.set
      SET_PARAMS: CCI_Shift
      TEST_REPORT_NAME: EA31337-CCI_Shift
