version: '3.4'
services:
  CCI_Period:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: CCI_Period
      RUN_ON_SET: set_opt_params CCI_Period $$(bc <<< "$$(input_get CCI_Period) - 2 * 4") $$(bc <<< "$$(input_get CCI_Period) + 2 * 4") 2
      SETFILE: /opt/sets/EA31337-CCI_Period.set
      TEST_REPORT_NAME: EA31337-CCI_Period
# @todo
# CCI_Period_Ratio:
#   command: run_backtest -v
#   image: ea31337/ea-tester:EURUSD-2018-DS
#   volumes:
#   - ./sets/EURUSD:/opt/sets:rw
#   - ./_results/EURUSD:/opt/_results:rw
#   env_file: ../../../EA-Tester.ini
#   environment:
#     SET_PARAMS: CCI_Period_Ratio
#     RUN_ON_SET: set_opt_params CCI_Period_Ratio $$(bc <<< "$$(input_get CCI_Period_Ratio) - 0.1 * 2") $$(bc <<< "$$(input_get CCI_Period_Ratio) + 0.1 * 2") 0.1
#     SETFILE: /opt/sets/EA31337-CCI_Period_Ratio.set
#     TEST_REPORT_NAME: EA31337-CCI_Period_Ratio
#   deploy:
#     restart_policy:
#       condition: none
  CCI_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: CCI_Applied_Price
      RUN_ON_SET: set_opt_params CCI_Applied_Price 0 6
      SETFILE: /opt/sets/EA31337-CCI_Applied_Price.set
      TEST_REPORT_NAME: EA31337-CCI_Applied_Price
    deploy:
      restart_policy:
        condition: none
  CCI_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: CCI_SignalLevel
      RUN_ON_SET: set_opt_params CCI_SignalLevel $$(bc <<< "$$(input_get CCI_SignalLevel) - 0.1 * 5") $$(bc <<< "$$(input_get CCI_SignalLevel) + 0.1 * 5") 0.1
      SETFILE: /opt/sets/EA31337-CCI_SignalLevel.set
      TEST_REPORT_NAME: EA31337-CCI_SignalLevel
    deploy:
      restart_policy:
        condition: none
  CCI_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: CCI_Shift
      RUN_ON_SET: set_opt_params CCI_Shift $$(bc <<< "$$(input_get CCI_Shift) - 1 * 2") $$(bc <<< "$$(input_get CCI_Shift) + 1 * 2")
      SETFILE: /opt/sets/EA31337-CCI_Shift.set
      TEST_REPORT_NAME: EA31337-CCI_Shift
    deploy:
      restart_policy:
        condition: none
