---
version: '3.4'
services:
  RSI1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SET_PARAMS: RSI1_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 7"))
        3
      SETFILE: /opt/sets/EA31337-RSI1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-RSI1_SignalMethod
  RSI5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SET_PARAMS: RSI5_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 7"))
        3
      SETFILE: /opt/sets/EA31337-RSI5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-RSI5_SignalMethod
  RSI15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SET_PARAMS: RSI15_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 7"))
        3
      SETFILE: /opt/sets/EA31337-RSI15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-RSI15_SignalMethod
  RSI30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SET_PARAMS: RSI30_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 7"))
        3
      SETFILE: /opt/sets/EA31337-RSI30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-RSI30_SignalMethod
