---
version: '3.4'
services:
  Bands1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands1_SignalMethod
      RUN_ON_SET: set_opt_params Bands1_SignalMethod -127 127
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-Bands1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Bands1_SignalMethod
  Bands5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands5_SignalMethod
      RUN_ON_SET: set_opt_params Bands5_SignalMethod -127 127
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=30
      SETFILE: /opt/sets/EA31337-Bands5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Bands5_SignalMethod
  Bands15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands15_SignalMethod
      RUN_ON_SET: set_opt_params Bands15_SignalMethod -127 127
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SETFILE: /opt/sets/EA31337-Bands15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Bands15_SignalMethod
  Bands30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands30_SignalMethod
      RUN_ON_SET: set_opt_params Bands30_SignalMethod -127 127
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      SETFILE: /opt/sets/EA31337-Bands30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Bands30_SignalMethod
