version: '3.4'
services:
  MA_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MA_TrailingStopMethod
      RUN_ON_SET: set_opt_params MA_TrailingStopMethod 1 -27 0
      SETFILE: /opt/sets/EA31337-MA_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-MA_TrailingStopMethod
    deploy:
      restart_policy:
        condition: none
  MA_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MA_TrailingProfitMethod
      RUN_ON_SET: set_opt_params MA_TrailingProfitMethod 1 -27 0
      SETFILE: /opt/sets/EA31337-MA_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-MA_TrailingProfitMethod
    deploy:
      restart_policy:
        condition: none
