---
version: '3.4'
services:
  WPR1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR1_SignalMethod
      RUN_ON_SET: set_opt_params WPR1_SignalMethod -63 63
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=15
      SETFILE: /opt/sets/EA31337-WPR1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-WPR1_SignalMethod
  WPR5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR5_SignalMethod
      RUN_ON_SET: set_opt_params WPR5_SignalMethod -63 63
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=15
      SETFILE: /opt/sets/EA31337-WPR5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-WPR5_SignalMethod
  WPR15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR15_SignalMethod
      RUN_ON_SET: set_opt_params WPR15_SignalMethod -63 63
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=15
      SETFILE: /opt/sets/EA31337-WPR15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-WPR15_SignalMethod
  WPR30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR30_SignalMethod
      RUN_ON_SET: set_opt_params WPR30_SignalMethod -63 63
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=15
      SETFILE: /opt/sets/EA31337-WPR30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-WPR30_SignalMethod
