---
version: '3.4'
services:
  AC_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      RUN_ON_SET: set_opt_params AC_TrailingStopMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-AC_TrailingStopMethod.set
      SET_PARAMS: AC_TrailingStopMethod
      TEST_REPORT_NAME: EA31337-AC_TrailingStopMethod
  AC_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      RUN_ON_SET: set_opt_params AC_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-AC_TrailingProfitMethod.set
      SET_PARAMS: AC_TrailingProfitMethod
      TEST_REPORT_NAME: EA31337-AC_TrailingProfitMethod
