---
version: '3.4'
services:
  AC_Active_Tf:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M1
      SETFILE: /opt/sets/EA31337-AC_Active_Tf.set
      SET_PARAMS: AC_Active_Tf
      TEST_REPORT_NAME: EA31337-AC_Active_Tf
