version: '3.4'
services:
  DeMarker_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: DeMarker_TrailingStopMethod
      RUN_ON_SET: set_opt_params DeMarker_TrailingStopMethod 1 -27 0
      SETFILE: /opt/sets/EURUSD/EA31337-DeMarker_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-DeMarker_TrailingStopMethod
  DeMarker_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: DeMarker_TrailingProfitMethod
      RUN_ON_SET: set_opt_params DeMarker_TrailingProfitMethod 1 -27 0
      SETFILE: /opt/sets/EURUSD/EA31337-DeMarker_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-DeMarker_TrailingProfitMethod
