---
version: '3.4'
services:
  AD_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: AD_TrailingStopMethod
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=80
      RUN_ON_SET: set_opt_params AD_TrailingStopMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-AD_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-AD_TrailingStopMethod
  AD_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: AD_TrailingProfitMethod
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=80
      RUN_ON_SET: set_opt_params AD_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-AD_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-AD_TrailingProfitMethod
