version: '3.4'
services:
  Envelopes_MA_Period_M1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M1
      SETFILE: /opt/sets/EA31337-Envelopes_MA_Period_M1.set
      SET_PARAMS: Envelopes_MA_Period_M1
      RUN_ON_SET: set_opt_params Envelopes_MA_Period_M1 $$(get_max 2 $$(bc <<< "$$(input_get Envelopes_MA_Period_M1) - 2 * 4")) $$(bc <<< "$$(input_get Envelopes_MA_Period_M1) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Period_M1
    deploy:
      restart_policy:
        condition: none
  Envelopes_MA_Period_M5:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M5
      SET_PARAMS: Envelopes_MA_Period_M5
      SETFILE: /opt/sets/EA31337-Envelopes_MA_Period_M5.set
      RUN_ON_SET: set_opt_params Envelopes_MA_Period_M5 $$(get_max 2 $$(bc <<< "$$(input_get Envelopes_MA_Period_M5) - 2 * 4")) $$(bc <<< "$$(input_get Envelopes_MA_Period_M5) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Period_M5
    deploy:
      restart_policy:
        condition: none
  Envelopes_MA_Period_M15:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M15
      SET_PARAMS: Envelopes_MA_Period_M15
      SETFILE: /opt/sets/EA31337-Envelopes_MA_Period_M15.set
      RUN_ON_SET: set_opt_params Envelopes_MA_Period_M15 $$(get_max 2 $$(bc <<< "$$(input_get Envelopes_MA_Period_M15) - 2 * 4")) $$(bc <<< "$$(input_get Envelopes_MA_Period_M15) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Period_M15
    deploy:
      restart_policy:
        condition: none
  Envelopes_MA_Period_M30:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M30
      SET_PARAMS: Envelopes_MA_Period_M30
      SETFILE: /opt/sets/EA31337-Envelopes_MA_Period_M30.set
      RUN_ON_SET: set_opt_params Envelopes_MA_Period_M30 $$(get_max 2 $$(bc <<< "$$(input_get Envelopes_MA_Period_M30) - 2 * 4")) $$(bc <<< "$$(input_get Envelopes_MA_Period_M30) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Period_M30
    deploy:
      restart_policy:
        condition: none
  Envelopes_MA_Method:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_MA_Method
      RUN_ON_SET: set_opt_params Envelopes_MA_Method 0 3
      SETFILE: /opt/sets/EA31337-Envelopes_MA_Method.set
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Method
    deploy:
      restart_policy:
        condition: none
  Envelopes_MA_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_MA_Shift
      RUN_ON_SET: set_opt_params Envelopes_MA_Shift $$(get_max 0 $$(bc <<< "$$(input_get Envelopes_MA_Shift) - 1 * 4")) $$(bc <<< "$$(input_get Envelopes_MA_Shift) + 1 * 4")
      SETFILE: /opt/sets/EA31337-Envelopes_MA_Shift.set
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Shift
    deploy:
      restart_policy:
        condition: none
  Envelopes_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Shift
      RUN_ON_SET: set_opt_params Envelopes_Shift $$(get_max 0 $$(bc <<< "$$(input_get Envelopes_Shift) - 1 * 4")) $$(bc <<< "$$(input_get Envelopes_Shift) + 1 * 4")
      SETFILE: /opt/sets/EA31337-Envelopes_Shift.set
      TEST_REPORT_NAME: EA31337-Envelopes_Shift
    deploy:
      restart_policy:
        condition: none
  Envelopes_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Applied_Price
      RUN_ON_SET: set_opt_params Envelopes_Applied_Price 0 6
      SETFILE: /opt/sets/EA31337-Envelopes_Applied_Price.set
      TEST_REPORT_NAME: EA31337-Envelopes_Applied_Price
    deploy:
      restart_policy:
        condition: none
  Envelopes_Deviation:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Deviation
      RUN_ON_SET: set_opt_params Envelopes_Deviation $$(bc <<< "$$(input_get Envelopes_Deviation) - 0.1 * 2") $$(bc <<< "$$(input_get Envelopes_Deviation) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EA31337-Envelopes_Deviation.set
      TEST_REPORT_NAME: EA31337-Envelopes_Deviation
    deploy:
      restart_policy:
        condition: none
  Envelopes_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    environment:
      SET_PARAMS: Envelopes_SignalLevel
      RUN_ON_SET: set_opt_params Envelopes_SignalLevel $$(bc <<< "$$(input_get Envelopes_SignalLevel) - 0.1 * 2") $$(bc <<< "$$(input_get Envelopes_SignalLevel) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EA31337-Envelopes_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Envelopes_SignalLevel
    deploy:
      restart_policy:
        condition: none
