version: '3.4'
services:
  Envelopes_MA_Period:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_MA_Period
      RUN_ON_SET: set_opt_params Envelopes_MA_Period $$(bc <<< "$$(input_get Envelopes_MA_Period) - 2 * 4") $$(bc <<< "$$(input_get Envelopes_MA_Period) + 2 * 4") 2
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_MA_Period.set
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Period
      BT_DEST: /opt/_results/EURUSD
  Envelopes_MA_Period_Ratio:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_MA_Period_Ratio
      RUN_ON_SET: set_opt_params Envelopes_MA_Period_Ratio $$(bc <<< "$$(input_get Envelopes_MA_Period_Ratio) - 0.1 * 2") $$(bc <<< "$$(input_get Envelopes_MA_Period_Ratio) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_MA_Period_Ratio.set
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Period_Ratio
      BT_DEST: /opt/_results/EURUSD
  Envelopes_MA_Method:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_MA_Method
      RUN_ON_SET: set_opt_params Envelopes_MA_Method 0 3
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_MA_Method.set
      TEST_REPORT_NAME: EA31337-Envelopes_MA_Method
      BT_DEST: /opt/_results/EURUSD
  Envelopes_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Shift
      RUN_ON_SET: set_opt_params Envelopes_Shift $$(bc <<< "$$(input_get DeMarker_Shift) - 1 * 2") $$(bc <<< "$$(input_get DeMarker_Shift) + 1 * 2")
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_Shift.set
      TEST_REPORT_NAME: EA31337-Envelopes_Shift
      BT_DEST: /opt/_results/EURUSD
  Envelopes_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Applied_Price
      RUN_ON_SET: set_opt_params Envelopes_Applied_Price 0 6
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_Applied_Price.set
      TEST_REPORT_NAME: EA31337-Envelopes_Applied_Price
      BT_DEST: /opt/_results/EURUSD
  Envelopes_Deviation:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Deviation
      RUN_ON_SET: set_opt_params Envelopes_Deviation $$(bc <<< "$$(input_get Envelopes_Deviation) - 0.1 * 2") $$(bc <<< "$$(input_get Envelopes_Deviation) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_Deviation.set
      TEST_REPORT_NAME: EA31337-Envelopes_Deviation
      BT_DEST: /opt/_results/EURUSD
  Envelopes_Deviation_Ratio:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Deviation_Ratio
      RUN_ON_SET: set_opt_params Envelopes_Deviation_Ratio $$(bc <<< "$$(input_get Envelopes_Deviation_Ratio) - 0.1 * 2") $$(bc <<< "$$(input_get Envelopes_Deviation_Ratio) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_Deviation_Ratio.set
      TEST_REPORT_NAME: EA31337-Envelopes_Deviation_Ratio
      BT_DEST: /opt/_results/EURUSD
# @todo
#  Envelopes_SignalLevel:
#    command: run_backtest -v
#   image: ea31337/ea-tester:EURUSD-2018-DS
#   volumes:
#   - ./sets:/opt/sets:rw
#   - ./_results/EURUSD:/opt/_results/EURUSD:rw
#   environment:
#     SET_PARAMS: Envelopes_SignalLevel 
#     RUN_ON_SET: set_opt_params Envelopes_SignalLevel $$(bc <<< "$$(input_get Envelopes_SignalLevel) - 0.1 * 2") $$(bc <<< "$$(input_get Envelopes_SignalLevel) + 0.1 * 2") 0.1
#     SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_SignalLevel.set
#     TEST_REPORT_NAME: EA31337-Envelopes_SignalLevel
      BT_DEST: /opt/_results/EURUSD
  Envelopes_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Shift
      RUN_ON_SET: set_opt_params Envelopes_Shift $$(bc <<< "$$(input_get Envelopes_Shift) - 1 * 2") $$(bc <<< "$$(input_get Envelopes_Shift) + 1 * 2")
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_Shift.set
      TEST_REPORT_NAME: EA31337-Envelopes_Shift
      BT_DEST: /opt/_results/EURUSD
  Envelopes_Deviation:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Deviation
      RUN_ON_SET: set_opt_params Envelopes_Deviation $$(bc <<< "$$(input_get Envelopes_Deviation) - 0.1 * 5") $$(bc <<< "$$(input_get Envelopes_Deviation) + 0.1 * 5") 0.1
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_Deviation.set
      TEST_REPORT_NAME: EA31337-Envelopes_Deviation
      BT_DEST: /opt/_results/EURUSD
  Envelopes_Deviation_Ratio:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes_Deviation_Ratio
      RUN_ON_SET: set_opt_params Envelopes_Deviation_Ratio $$(bc <<< "$$(input_get Envelopes_Deviation_Ratio) - 0.1 * 2") $$(bc <<< "$$(input_get Envelopes_Deviation_Ratio) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EURUSD/EA31337-Envelopes_Deviation_Ratio.set
      TEST_REPORT_NAME: EA31337-Envelopes_Deviation_Ratio
      BT_DEST: /opt/_results/EURUSD
