---
version: '3.4'
services:
  AC1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      RUN_ON_SET: set_opt_params AC1_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AC1_SignalMethod.set
      SET_PARAMS: AC1_SignalMethod
      TEST_REPORT_NAME: EA31337-AC1_SignalMethod
  AC5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=30
      RUN_ON_SET: set_opt_params AC5_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AC5_SignalMethod.set
      SET_PARAMS: AC5_SignalMethod
      TEST_REPORT_NAME: EA31337-AC5_SignalMethod
  AC15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: set_opt_params AC15_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AC15_SignalMethod.set
      SET_PARAMS: AC15_SignalMethod
      TEST_REPORT_NAME: EA31337-AC15_SignalMethod
  AC30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: set_opt_params AC30_SignalMethod -1 1
      SETFILE: /opt/sets/EA31337-AC30_SignalMethod.set
      SET_PARAMS: AC30_SignalMethod
      TEST_REPORT_NAME: EA31337-AC30_SignalMethod
