version: '3.4'
services:
  RSI_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI_TrailingStopMethod
      RUN_ON_SET: set_opt_params RSI_TrailingStopMethod 1 -27 0
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EURUSD/EA31337-RSI_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-RSI_TrailingStopMethod
    deploy:
      restart_policy:
        condition: none
  RSI_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: RSI_TrailingProfitMethod
      RUN_ON_SET: set_opt_params RSI_TrailingProfitMethod 1 -27 0
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EURUSD/EA31337-RSI_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-RSI_TrailingProfitMethod
    deploy:
      restart_policy:
        condition: none
