version: '3.4'
services:
  DeMarker_Period:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: DeMarker_Period
      RUN_ON_SET: set_opt_params DeMarker_Period $$(bc <<< "$$(input_get DeMarker_Period) - 2 * 4") $$(bc <<< "$$(input_get DeMarker_Period) + 2 * 4") 2
      SETFILE: /opt/sets/EA31337-DeMarker_Period.set
      TEST_REPORT_NAME: EA31337-DeMarker_Period
    deploy:
      restart_policy:
        condition: none
  DeMarker_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: DeMarker_SignalLevel
      RUN_ON_SET: set_opt_params DeMarker_SignalLevel $$(bc <<< "$$(input_get DeMarker_SignalLevel) - 0.1 * 2") $$(bc <<< "$$(input_get DeMarker_SignalLevel) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EA31337-DeMarker_SignalLevel.set
      TEST_REPORT_NAME: EA31337-DeMarker_SignalLevel
    deploy:
      restart_policy:
        condition: none
  DeMarker_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: DeMarker_Shift
      RUN_ON_SET: set_opt_params DeMarker_Shift $$(bc <<< "$$(input_get DeMarker_Shift) - 1 * 2") $$(bc <<< "$$(input_get DeMarker_Shift) + 1 * 2")
      SETFILE: /opt/sets/EA31337-DeMarker_Shift.set
      TEST_REPORT_NAME: EA31337-DeMarker_Shift
    deploy:
      restart_policy:
        condition: none
