---
version: '3.4'
services:
  DeMarker_Period_M1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
      SETFILE: /opt/sets/EA31337-DeMarker_Period_M1.set
      SET_PARAMS: DeMarker_Period_M1
      RUN_ON_SET: set_opt_params DeMarker_Period_M1 $$(get_max 2 $$(bc <<< "$$(input_get DeMarker_Period_M1) - 2 * 8")) $$(bc <<< "$$(input_get DeMarker_Period_M1) + 2 * 8") 2
      TEST_REPORT_NAME: EA31337-DeMarker_Period_M1
  DeMarker_Period_M5:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
      SET_PARAMS: DeMarker_Period_M5
      SETFILE: /opt/sets/EA31337-DeMarker_Period_M5.set
      RUN_ON_SET: set_opt_params DeMarker_Period_M5 $$(get_max 2 $$(bc <<< "$$(input_get DeMarker_Period_M5) - 2 * 8")) $$(bc <<< "$$(input_get DeMarker_Period_M5) + 2 * 8") 2
      TEST_REPORT_NAME: EA31337-DeMarker_Period_M5
  DeMarker_Period_M15:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
      SET_PARAMS: DeMarker_Period_M15
      SETFILE: /opt/sets/EA31337-DeMarker_Period_M15.set
      RUN_ON_SET: set_opt_params DeMarker_Period_M15 $$(get_max 2 $$(bc <<< "$$(input_get DeMarker_Period_M15) - 2 * 8")) $$(bc <<< "$$(input_get DeMarker_Period_M15) + 2 * 8") 2
      TEST_REPORT_NAME: EA31337-DeMarker_Period_M15
  DeMarker_Period_M30:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
      SET_PARAMS: DeMarker_Period_M30
      SETFILE: /opt/sets/EA31337-DeMarker_Period_M30.set
      RUN_ON_SET: set_opt_params DeMarker_Period_M30 $$(get_max 2 $$(bc <<< "$$(input_get DeMarker_Period_M30) - 2 * 8")) $$(bc <<< "$$(input_get DeMarker_Period_M30) + 2 * 8") 2
      TEST_REPORT_NAME: EA31337-DeMarker_Period_M30
  DeMarker_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: DeMarker_SignalLevel
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
      RUN_ON_SET: set_opt_params DeMarker_SignalLevel $$(bc <<< "$$(input_get DeMarker_SignalLevel) - 0.1 * 5") $$(bc <<< "$$(input_get DeMarker_SignalLevel) + 0.1 * 5") 0.1
      SETFILE: /opt/sets/EA31337-DeMarker_SignalLevel.set
      TEST_REPORT_NAME: EA31337-DeMarker_SignalLevel
  DeMarker_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: DeMarker_Shift
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
      RUN_ON_SET: set_opt_params DeMarker_Shift $$(bc <<< "$$(input_get DeMarker_Shift) - 1 * 4") $$(bc <<< "$$(input_get DeMarker_Shift) + 1 * 4")
      SETFILE: /opt/sets/EA31337-DeMarker_Shift.set
      TEST_REPORT_NAME: EA31337-DeMarker_Shift
