version: '3.4'
services:
  MFI_Period_M1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M1
      SETFILE: /opt/sets/EA31337-MFI_Period_M1.set
      SET_PARAMS: MFI_Period_M1
      RUN_ON_SET: set_opt_params MFI_Period_M1 $$(get_max 2 $$(bc <<< "$$(input_get MFI_Period_M1) - 2 * 4")) $$(bc <<< "$$(input_get MFI_Period_M1) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-MFI_Period_M1
    deploy:
      restart_policy:
        condition: none
  MFI_Period_M5:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M5
      SET_PARAMS: MFI_Period_M5
      SETFILE: /opt/sets/EA31337-MFI_Period_M5.set
      RUN_ON_SET: set_opt_params MFI_Period_M5 $$(get_max 2 $$(bc <<< "$$(input_get MFI_Period_M5) - 2 * 4")) $$(bc <<< "$$(input_get MFI_Period_M5) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-MFI_Period_M5
    deploy:
      restart_policy:
        condition: none
  MFI_Period_M15:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M15
      SET_PARAMS: MFI_Period_M15
      SETFILE: /opt/sets/EA31337-MFI_Period_M15.set
      RUN_ON_SET: set_opt_params MFI_Period_M15 $$(get_max 2 $$(bc <<< "$$(input_get MFI_Period_M15) - 2 * 4")) $$(bc <<< "$$(input_get MFI_Period_M15) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-MFI_Period_M15
    deploy:
      restart_policy:
        condition: none
  MFI_Period_M30:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_PERIOD: M30
      SET_PARAMS: MFI_Period_M30
      SETFILE: /opt/sets/EA31337-MFI_Period_M30.set
      RUN_ON_SET: set_opt_params MFI_Period_M30 $$(get_max 2 $$(bc <<< "$$(input_get MFI_Period_M30) - 2 * 4")) $$(bc <<< "$$(input_get MFI_Period_M30) + 2 * 4") 2
      TEST_REPORT_NAME: EA31337-MFI_Period_M30
    deploy:
      restart_policy:
        condition: none
  MFI_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: MFI_SignalLevel
      RUN_ON_SET: set_opt_params MFI_SignalLevel $$(bc <<< "$$(input_get MFI_SignalLevel) - 0.1 * 5") $$(bc <<< "$$(input_get MFI_SignalLevel) + 0.1 * 5") 0.1
      SETFILE: /opt/sets/EA31337-MFI_SignalLevel.set
      TEST_REPORT_NAME: EA31337-MFI_SignalLevel
    deploy:
      restart_policy:
        condition: none
  MFI_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    environment:
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=90
      SET_PARAMS: MFI_Shift
      RUN_ON_SET: set_opt_params MFI_Shift $$(bc <<< "$$(input_get MFI_Shift) - 1 * 2") $$(bc <<< "$$(input_get MFI_Shift) + 1 * 2")
      SETFILE: /opt/sets/EA31337-MFI_Shift.set
      TEST_REPORT_NAME: EA31337-MFI_Shift
    deploy:
      restart_policy:
        condition: none
