version: '3.4'
services:
  CCI_Active:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: CCI1_Active,CCI5_Active,CCI15_Active,CCI30_Active
      SETFILE: /opt/sets/EA31337-CCI_Active.set
      TEST_REPORT_NAME: EA31337-CCI_Active
    deploy:
      restart_policy:
        condition: none
