---
version: '3.4'
services:
  CCI1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 5"))
        3
      SETFILE: /opt/sets/EA31337-CCI1_SignalMethod.set
      SET_PARAMS: CCI1_SignalMethod
      TEST_REPORT_NAME: EA31337-CCI1_SignalMethod
  CCI5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 5"))
        3
      SETFILE: /opt/sets/EA31337-CCI5_SignalMethod.set
      SET_PARAMS: CCI5_SignalMethod
      TEST_REPORT_NAME: EA31337-CCI5_SignalMethod
  CCI15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 5"))
        3
      SETFILE: /opt/sets/EA31337-CCI15_SignalMethod.set
      SET_PARAMS: CCI15_SignalMethod
      TEST_REPORT_NAME: EA31337-CCI15_SignalMethod
  CCI30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=5
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -63 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 3 * 5"))
        $$(get_min 63 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 3 * 5"))
        3
      SETFILE: /opt/sets/EA31337-CCI30_SignalMethod.set
      SET_PARAMS: CCI30_SignalMethod
      TEST_REPORT_NAME: EA31337-CCI30_SignalMethod
