version: '3.4'
services:
  WPR_Period:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR_Period
      RUN_ON_SET: set_opt_params WPR_Period $$(bc <<< "$$(input_get WPR_Period) - 2 * 4") $$(bc <<< "$$(input_get WPR_Period) + 2 * 4") 2
      SETFILE: /opt/sets/EA31337-WPR_Period.set
      TEST_REPORT_NAME: EA31337-WPR_Period
  WPR_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    environment:
      SET_PARAMS: WPR_SignalLevel
      RUN_ON_SET: set_opt_params WPR_SignalLevel $$(bc <<< "$$(input_get WPR_SignalLevel) - 0.1 * 2") $$(bc <<< "$$(input_get WPR_SignalLevel) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EA31337-WPR_SignalLevel.set
      TEST_REPORT_NAME: EA31337-WPR_SignalLevel
    deploy:
      restart_policy:
        condition: none
  WPR_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    environment:
      SET_PARAMS: WPR_Shift
      RUN_ON_SET: set_opt_params WPR_Shift $$(bc <<< "$$(input_get WPR_Shift) - 1 * 2") $$(bc <<< "$$(input_get WPR_Shift) + 1 * 2")
      SETFILE: /opt/sets/EA31337-WPR_Shift.set
      TEST_REPORT_NAME: EA31337-WPR_Shift
    deploy:
      restart_policy:
        condition: none
