---
version: '3.4'
services:
  Envelopes1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes1_SignalMethod
      RUN_ON_SET: set_opt_params Envelopes1_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-Envelopes1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes1_SignalMethod
  Envelopes5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes5_SignalMethod
      RUN_ON_SET: set_opt_params Envelopes5_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-Envelopes5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes5_SignalMethod
  Envelopes15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes15_SignalMethod
      RUN_ON_SET: set_opt_params Envelopes15_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-Envelopes15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes15_SignalMethod
  Envelopes30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Envelopes30_SignalMethod
      RUN_ON_SET: set_opt_params Envelopes30_SignalMethod -127 127
      SETFILE: /opt/sets/EA31337-Envelopes30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes30_SignalMethod
