---
version: '3.4'
services:
  Envelopes1_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M1
      SET_PARAMS: Envelopes1_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      SETFILE: /opt/sets/EA31337-Envelopes1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes1_SignalMethod
  Envelopes5_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M5
      SET_PARAMS: Envelopes5_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      SETFILE: /opt/sets/EA31337-Envelopes5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes5_SignalMethod
  Envelopes15_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M15
      SET_PARAMS: Envelopes15_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      SETFILE: /opt/sets/EA31337-Envelopes15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes15_SignalMethod
  Envelopes30_SignalMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M30
      SET_PARAMS: Envelopes30_SignalMethod
      RUN_ON_SET: >
        set_opt_params "$${SET_PARAMS}"
        $$(get_max -127 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 7 * 5"))
        $$(get_min 127 $$(bc <<< "$$(input_get $${SET_PARAMS}) + 7 * 7"))
        7
      SETFILE: /opt/sets/EA31337-Envelopes30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Envelopes30_SignalMethod
