version: '3.4'
services:
  WPR_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR_TrailingStopMethod
      RUN_ON_SET: set_opt_params WPR_TrailingStopMethod 1 -27 0
      SETFILE: /opt/sets/EA31337-WPR_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-WPR_TrailingStopMethod
    deploy:
      restart_policy:
        condition: none
  WPR_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: WPR_TrailingProfitMethod
      RUN_ON_SET: set_opt_params WPR_TrailingProfitMethod 1 -27 0
      SETFILE: /opt/sets/EA31337-WPR_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-WPR_TrailingProfitMethod
    deploy:
      restart_policy:
        condition: none
