---
version: '3.4'
services:
  SAR_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR_TrailingStopMethod
      RUN_ON_SET: set_opt_params SAR_TrailingStopMethod 1 -25 0
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-SAR_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-SAR_TrailingStopMethod
  SAR_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: SAR_TrailingProfitMethod
      RUN_ON_SET: set_opt_params SAR_TrailingProfitMethod 1 -25 0
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=20
      SETFILE: /opt/sets/EA31337-SAR_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-SAR_TrailingProfitMethod
