---
version: '3.4'
services:
  SAR_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=40
      RUN_ON_SET: set_opt_params SAR_TrailingStopMethod 1 -25 0
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-SAR_TrailingProfitMethod.set
      SETFILE: /opt/sets/EA31337-SAR_TrailingStopMethod.set
      SET_PARAMS: SAR_TrailingStopMethod
      TEST_REPORT_NAME: EA31337-SAR_TrailingStopMethod
  SAR_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=40
      RUN_ON_SET: set_opt_params SAR_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-SAR_TrailingProfitMethod.set
      SET_PARAMS: SAR_TrailingProfitMethod
      TEST_REPORT_NAME: EA31337-SAR_TrailingProfitMethod
