version: '3.4'
services:
  Alligator_Periods:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_Periods
      RUN_ON_SET: for p in Lips Teeth Jaw; do set_opt_params "Alligator_Period_$${p}" $$(bc <<< "$$(input_get Alligator_Period_$${p}) - 2") $$(bc <<< "$$(input_get Alligator_Period_$${p}) + 2") 2; done
      SETFILE: /opt/sets/EURUSD/EA31337-Alligator_Periods.set
      TEST_REPORT_NAME: EA31337-Alligator_Periods
      BT_DEST: /opt/_results/EURUSD
  Alligator_Period_Ratio:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_Period_Ratio
      RUN_ON_SET: set_opt_params Alligator_Period_Ratio $$(bc <<< "$$(input_get Alligator_Period_Ratio) - 0.1 * 2") $$(bc <<< "$$(input_get Alligator_Period_Ratio) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EURUSD/EA31337-Alligator_Period_Ratio.set
      TEST_REPORT_NAME: EA31337-Alligator_Period_Ratio
      BT_DEST: /opt/_results/EURUSD
  Alligator_Applied_Price:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_Applied_Price
      RUN_ON_SET: set_opt_params Alligator_Applied_Price 0 6
      SETFILE: /opt/sets/EURUSD/EA31337-Alligator_Applied_Price.set
      TEST_REPORT_NAME: EA31337-Alligator_Applied_Price
      BT_DEST: /opt/_results/EURUSD
  Alligator_SignalLevel:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_SignalLevel
      RUN_ON_SET: set_opt_params Alligator_SignalLevel $$(bc <<< "$$(input_get Alligator_SignalLevel) - 0.1 * 2") $$(bc <<< "$$(input_get Alligator_SignalLevel) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EURUSD/EA31337-Alligator_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Alligator_SignalLevel
      BT_DEST: /opt/_results/EURUSD
  Alligator_Shift:
    command: run_backtest -v
    build:
      context: ../../..
      target: eurusd-2018
    image: ea31337:eurusd-2018
    volumes:
    - ./sets:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results/EURUSD:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_Shift
      RUN_ON_SET: for p in Shift_Jaw Shift_Teeth Shift_Lips Shift Shift_Far; do set_opt_params "Alligator_$${p}" $$(bc <<< "$$(input_get Alligator_$${p}) - 1") $$(bc <<< "$$(input_get Alligator_$${p}) + 1"); done
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=1
      SETFILE: /opt/sets/EURUSD/EA31337-Alligator_Shift.set
      TEST_REPORT_NAME: EA31337-Alligator_Shift
      BT_DEST: /opt/_results/EURUSD
