version: '3.4'
services:
  Alligator_Periods:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_Periods
      RUN_ON_SET: for p in Lips Teeth Jaw; do set_opt_params "Alligator_Period_$${p}" $$(bc <<< "$$(input_get Alligator_Period_$${p}) - 2") $$(bc <<< "$$(input_get Alligator_Period_$${p}) + 2") 2; done
      SETFILE: /opt/sets/EA31337-Alligator_Periods.set
      TEST_REPORT_NAME: EA31337-Alligator_Periods
    deploy:
      restart_policy:
        condition: none
  Alligator_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_Applied_Price
      RUN_ON_SET: set_opt_params Alligator_Applied_Price 0 6
      SETFILE: /opt/sets/EA31337-Alligator_Applied_Price.set
      TEST_REPORT_NAME: EA31337-Alligator_Applied_Price
    deploy:
      restart_policy:
        condition: none
  Alligator_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_SignalLevel
      RUN_ON_SET: set_opt_params Alligator_SignalLevel $$(bc <<< "$$(input_get Alligator_SignalLevel) - 0.1 * 2") $$(bc <<< "$$(input_get Alligator_SignalLevel) + 0.1 * 2") 0.1
      SETFILE: /opt/sets/EA31337-Alligator_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Alligator_SignalLevel
    deploy:
      restart_policy:
        condition: none
  Alligator_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Alligator_Shift
      RUN_ON_SET: for p in Shift_Jaw Shift_Teeth Shift_Lips Shift Shift_Far; do set_opt_params "Alligator_$${p}" $$(bc <<< "$$(input_get Alligator_$${p}) - 1") $$(bc <<< "$$(input_get Alligator_$${p}) + 1"); done
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=1
      SETFILE: /opt/sets/EA31337-Alligator_Shift.set
      TEST_REPORT_NAME: EA31337-Alligator_Shift
    deploy:
      restart_policy:
        condition: none
