---
version: '3.4'
services:
  Alligator_Period_Jaw_Lips:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 10-12
      BT_TESTMODEL: 1
      BT_TESTMODEL_FXT: 1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=0.8
      RUN_ON_SET: >
        for p in Jaw Lips; do
        set_opt_params "Alligator_Period_$${p}"
        $$(bc <<< "$$(input_get Alligator_Period_$${p}) - 8")
        $$(bc <<< "$$(input_get Alligator_Period_$${p}) + 8")
        4;
        done
      SETFILE: /opt/sets/EA31337-Alligator_Periods.set
      SET_PARAMS: Alligator_Period_Jaw,Alligator_Lips
      TEST_REPORT_NAME: EA31337-Alligator_Periods
  Alligator_Period_Jaw_Teeth:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 10-12
      BT_TESTMODEL: 1
      BT_TESTMODEL_FXT: 1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=0.8
      RUN_ON_SET: >
        for p in Jaw Teeth; do
        set_opt_params "Alligator_Period_$${p}"
        $$(bc <<< "$$(input_get Alligator_Period_$${p}) - 8")
        $$(bc <<< "$$(input_get Alligator_Period_$${p}) + 8")
        4;
        done
      SETFILE: /opt/sets/EA31337-Alligator_Periods.set
      SET_PARAMS: Alligator_Period_Jaw,Alligator_Period_Teeth
      TEST_REPORT_NAME: EA31337-Alligator_Periods
  Alligator_Period_Teeth_Lips:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 10-12
      BT_TESTMODEL: 1
      BT_TESTMODEL_FXT: 1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=0.8
      RUN_ON_SET: >
        for p in Teeth Lips; do
        set_opt_params "Alligator_Period_$${p}"
        $$(bc <<< "$$(input_get Alligator_Period_$${p}) - 8")
        $$(bc <<< "$$(input_get Alligator_Period_$${p}) + 8")
        4;
        done
      SETFILE: /opt/sets/EA31337-Alligator_Periods.set
      SET_PARAMS: Alligator_Period_Teeth,Alligator_Lips
      TEST_REPORT_NAME: EA31337-Alligator_Periods
  Alligator_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=4
      RUN_ON_SET: set_opt_params Alligator_Applied_Price 0 6
      SETFILE: /opt/sets/EA31337-Alligator_Applied_Price.set
      SET_PARAMS: Alligator_Applied_Price
      TEST_REPORT_NAME: EA31337-Alligator_Applied_Price
  Alligator_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=4
      RUN_ON_SET: >
        set_opt_params Alligator_SignalLevel
        $$(bc <<< "$$(input_get Alligator_SignalLevel) - 0.1 * 2")
        $$(bc <<< "$$(input_get Alligator_SignalLevel) + 0.1 * 2")
        0.1
      SETFILE: /opt/sets/EA31337-Alligator_SignalLevel.set
      SET_PARAMS: Alligator_SignalLevel
      TEST_REPORT_NAME: EA31337-Alligator_SignalLevel
  Alligator_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=4
      RUN_ON_SET: >
        for p in Shift_Jaw Shift_Teeth Shift_Lips Shift; do
        set_opt_params "Alligator_$${p}"
        $$(bc <<< "$$(input_get Alligator_$${p}) - 1")
        $$(bc <<< "$$(input_get Alligator_$${p}) + 1")
        1;
        done
      SETFILE: /opt/sets/EA31337-Alligator_Shift.set
      SET_PARAMS: Alligator_Shift_Jaw,Alligator_Shift_Teeth,Alligator_Shift_Lips,Alligator_Shift
      TEST_REPORT_NAME: EA31337-Alligator_Shift
