---
version: '3.4'
services:
  Fractals_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Fractals_TrailingStopMethod
      RUN_ON_SET: set_opt_params Fractals_TrailingStopMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-Fractals_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-Fractals_TrailingStopMethod
  Fractals_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Fractals_TrailingProfitMethod
      RUN_ON_SET: set_opt_params Fractals_TrailingProfitMethod 1 -25 0
      SETFILE: /opt/sets/EA31337-Fractals_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-Fractals_TrailingProfitMethod
