---
name: Optimize Strategy Envelopes

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-envelopes'
      - 'optimize-strategy-envelopes-*'

jobs:
  Optimize-Indicator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_MA_Period_M1}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_MA_Period_M5}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_MA_Period_M15}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_MA_Period_M30}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_Deviation_M1}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_Deviation_M5}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_Deviation_M15}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_Deviation_M30}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_Applied_Price}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_SignalLevel}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_MA_Shift}
      - {working-directory: Strategies/Envelopes/Indicator, run: docker-compose run $DCA Envelopes_Shift}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Optimize-Stops:
    needs: Optimize-Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - {working-directory: Strategies/Envelopes/Stops, run: docker-compose run $DCA Envelopes_TrailingStopMethod}
      - {working-directory: Strategies/Envelopes/Stops, run: docker-compose run $DCA Envelopes_TrailingProfitMethod}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Optimize-SignalMethod:
    needs: Optimize-Stops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - {working-directory: Strategies/Envelopes/SignalMethod, run: docker-compose run $DCA Envelopes1_SignalMethod}
      - {working-directory: Strategies/Envelopes/SignalMethod, run: docker-compose run $DCA Envelopes5_SignalMethod}
      - {working-directory: Strategies/Envelopes/SignalMethod, run: docker-compose run $DCA Envelopes15_SignalMethod}
      - {working-directory: Strategies/Envelopes/SignalMethod, run: docker-compose run $DCA Envelopes30_SignalMethod}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  Optimize-Timeframes:
    needs: Optimize-SignalMethod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - {working-directory: Strategies/Envelopes/Timeframes, run: docker-compose run $DCA Envelopes_Active_Tf}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
