---
name: Optimize Strategy MFI

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-mfi'
      - 'optimize-strategy-mfi-*'

jobs:
  Indicator:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/MFI/Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA MFI_Period_M1
      - run: docker-compose run $DCA MFI_Period_M5
      - run: docker-compose run $DCA MFI_Period_M15
      - run: docker-compose run $DCA MFI_Period_M30
      - run: docker-compose run $DCA MFI_SignalLevel
      - run: docker-compose run $DCA MFI_Shift
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Stops:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/MFI/Stops
    needs: Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - {working-directory: Strategies/MFI/Stops, run: docker-compose run $DCA MFI_TrailingStopMethod}
      - {working-directory: Strategies/MFI/Stops, run: docker-compose run $DCA MFI_TrailingProfitMethod}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  SignalMethod:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/MFI/SignalMethod
    needs: Stops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA MFI1_SignalMethod
      - run: docker-compose run $DCA MFI5_SignalMethod
      - run: docker-compose run $DCA MFI15_SignalMethod
      - run: docker-compose run $DCA MFI30_SignalMethod
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/MFI/Timeframes
    needs: SignalMethod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA MFI_Active_Tf
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
