---
name: Optimize Strategy MA

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-ma'
      - 'optimize-strategy-ma-*'

jobs:
  Optimize-Indicator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - {working-directory: Strategies/MA/Indicator, run: docker-compose run $DCA MA_Periods}
      - {working-directory: Strategies/MA/Indicator, run: docker-compose run $DCA MA_Applied_Price}
      - {working-directory: Strategies/MA/Indicator, run: docker-compose run $DCA MA_SignalLevel}
      - {working-directory: Strategies/MA/Indicator, run: docker-compose run $DCA MA_Shift}
      - {working-directory: Strategies/MA/Indicator, run: docker-compose run $DCA MA_Shift_Fast}
      - {working-directory: Strategies/MA/Indicator, run: docker-compose run $DCA MA_Shift_Medium}
      - {working-directory: Strategies/MA/Indicator, run: docker-compose run $DCA MA_Shift_Slow}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  Optimize-Stops:
    needs: Optimize-Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - {working-directory: Strategies/MA/Stops, run: docker-compose run $DCA MA_TrailingStopMethod}
      - {working-directory: Strategies/MA/Stops, run: docker-compose run $DCA MA_TrailingProfitMethod}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Optimize-SignalMethod:
    needs: Optimize-Stops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - {working-directory: Strategies/MA/SignalMethod, run: docker-compose run $DCA MA1_SignalMethod}
      - {working-directory: Strategies/MA/SignalMethod, run: docker-compose run $DCA MA5_SignalMethod}
      - {working-directory: Strategies/MA/SignalMethod, run: docker-compose run $DCA MA15_SignalMethod}
      - {working-directory: Strategies/MA/SignalMethod, run: docker-compose run $DCA MA30_SignalMethod}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Optimize-Timeframes:
    needs: Optimize-SignalMethod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - {working-directory: Strategies/MA/Timeframes, run: docker-compose run $DCA MA_Active_Tf}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
