---
name: Optimize Strategy Alligator

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-alligator'
      - 'optimize-strategy-alligator-*'

jobs:
  Periods:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/Alligator/Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA Alligator_Periods
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Indicator:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/Alligator/Indicator
    needs: Periods
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA Alligator_Applied_Price
      - run: docker-compose run $DCA Alligator_Shift
      - run: docker-compose run $DCA Alligator_SignalLevel
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Stops:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/Alligator/Stops
    needs: Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA Alligator_TrailingStopMethod
      - run: docker-compose run $DCA Alligator_TrailingProfitMethod
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  SignalMethod:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/Alligator/SignalMethod
    needs: Stops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA Alligator1_SignalMethod
      - run: docker-compose run $DCA Alligator5_SignalMethod
      - run: docker-compose run $DCA Alligator15_SignalMethod
      - run: docker-compose run $DCA Alligator30_SignalMethod
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    needs: SignalMethod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA Alligator_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
