# yamllint disable rule:line-length
---
name: Optimize Strategy RSI

on:
  push:
    branches:
      - 'optimize-strategy-rsi*'

jobs:
  Indicator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run RSI_Period_M1
        run: docker-compose run -e BT_MONTHS=1 RSI_Period_M1
        working-directory: Strategies/RSI/Indicator
