---
name: Optimize SmartQueue

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-smartqueue'
      - 'optimize-smartqueue-*'

jobs:
  Optimize-SmartQueue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run SmartQueueMethod
        working-directory: SmartQueue
      - run: docker-compose run SmartQueueFilter
        working-directory: SmartQueue
      - run: docker-compose run SmartQueueActive
        working-directory: SmartQueue
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
