---
name: Optimize Strategy SAR

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-sar'
      - 'optimize-strategy-sar-*'

jobs:
  Indicator:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/SAR/Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA SAR_Step
      - run: docker-compose run $DCA SAR_Maximum_Stop
      - run: docker-compose run $DCA SAR_Shift
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Stops:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/SAR/Stops
    needs: Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA SAR_TrailingStopMethod
      - run: docker-compose run $DCA SAR_TrailingProfitMethod
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  SignalMethod:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/SAR/SignalMethod
    needs: Stops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA SAR1_SignalMethod
      - run: docker-compose run $DCA SAR5_SignalMethod
      - run: docker-compose run $DCA SAR15_SignalMethod
      - run: docker-compose run $DCA SAR30_SignalMethod
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/SAR/Timeframes
    needs: SignalMethod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA SAR_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git add --renormalize .
          git commit -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
