---
name: Optimize Strategy CCI

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-cci'
      - 'optimize-strategy-cci-*'

jobs:
  Indicator:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/CCI/Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA CCI_SignalLevel
      - run: docker-compose run $DCA CCI_Shift
      - run: docker-compose run $DCA CCI_Applied_Price
      - run: docker-compose run $DCA CCI_Period_M1
      - run: docker-compose run $DCA CCI_Period_M5
      - run: docker-compose run $DCA CCI_Period_M15
      - run: docker-compose run $DCA CCI_Period_M30
      - run: docker-compose run $DCA CCI_SignalLevel
      - run: docker-compose run $DCA CCI_Shift
      - run: docker-compose run $DCA CCI_Applied_Price
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit --allow-empty -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Stops:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/CCI/Stops
    needs: Indicator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA CCI_TrailingStopMethod
      - run: docker-compose run $DCA CCI_TrailingProfitMethod
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit --allow-empty -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  SignalMethod:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/CCI/SignalMethod
    needs: Stops
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - CCI1_SignalMethod
          - CCI5_SignalMethod
          - CCI15_SignalMethod
          - CCI30_SignalMethod
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA ${{ matrix.test }}
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit --allow-empty -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Timeframes:
    defaults:
      run:
        shell: bash
        working-directory: Strategies/CCI/Timeframes
    needs: SignalMethod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run $DCA CCI_Active_Tf
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit --allow-empty -am "${{ github.workflow }}"
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
