---
name: Optimize All

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-all'
      - 'optimize-all-*'

jobs:
  Optimize-All:
    defaults:
      run:
        shell: bash
        working-directory: All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - run: docker-compose run CloseOrderAfterXHours
      - run: docker-compose run InitNoOfOrdersToCalcPF
      - run: docker-compose run LotSize
      - run: docker-compose run MaxOrders
      - run: docker-compose run MaxOrdersPerType
      - run: docker-compose run MinPipChangeToTrade
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --autostash --rebase -Xours
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
