---
name: Optimize Strategy AD

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-strategy-ad'
      - 'optimize-strategy-ad-*'

jobs:
  Optimize-Stops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - name: Run optimization tests
        run: docker-compose up
        working-directory: Strategies/AD/Stops
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --rebase --autostash
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  Optimize-SignalMethod:
    needs: Optimize-Stops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
      - {working-directory: Strategies/AD/SignalMethod, run: docker-compose run $DCA AD1_SignalMethod}
      - {working-directory: Strategies/AD/SignalMethod, run: docker-compose run $DCA AD5_SignalMethod}
      - {working-directory: Strategies/AD/SignalMethod, run: docker-compose run $DCA AD15_SignalMethod}
      - {working-directory: Strategies/AD/SignalMethod, run: docker-compose run $DCA AD30_SignalMethod}
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --rebase --autostash
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      DCA: "--rm"
  Optimize-Timeframes:
    needs: Optimize-Stops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - name: Run optimization tests
        run: docker-compose up
        working-directory: Strategies/AD/Timeframes
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin ${{ github.ref }} --rebase --autostash
          git commit -m "Adds test results" -a
      - name: Git Diff
        run: NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
