---
name: Validate

# yamllint disable rule:truthy
on:
  push:
    branches:
      - 'optimize-validate'

jobs:
  Validate-Strategies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false  # Otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
          fetch-depth: 0  # Otherwise, you will failed to push refs to dest repo.
      - name: Run tests in dry mode...
        run: |
          find "${{ github.workspace }}" -name docker-compose.yml \
            -exec bash -c \
              "echo docker-compose -f '{}' run $DCA;" \
            ';'
        shell: bash
    env:
      DCA: "--rm -e OPT_DRY_RUN=1"
