---
version: '3.4'
services:
  Bands_Deviation_M1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_Deviation_M1
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 0.1 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 0.1 * 8"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 0.1 * 8")
        0.4
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Period_M1.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_Deviation_M1.set
      TEST_REPORT_NAME: EA31337-Bands_Deviation_M1
  Bands_Deviation_M5:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_Deviation_M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 0.1 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 0.1 * 8"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 0.1 * 8")
        0.4
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Period_M5.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      SETFILE: /opt/sets/EA31337-Bands_Deviation_M5.set
      TEST_REPORT_NAME: EA31337-Bands_Deviation_M5
  Bands_Deviation_M15:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_Deviation_M15
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 0.1 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 0.1 * 8"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 0.1 * 8")
        0.4
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Period_M15.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_Deviation_M15.set
      TEST_REPORT_NAME: EA31337-Bands_Deviation_M15
  Bands_Deviation_M30:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_Deviation_M30
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 0.1 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 0.1 * 8"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 0.1 * 8")
        0.4
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Period_M30.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_Deviation_M30.set
      TEST_REPORT_NAME: EA31337-Bands_Deviation_M30
  Bands_Period_M1:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M1
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_Period_M1.set
      SET_PARAMS: Bands_Period_M1
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 2 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 2 * 8"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 2 * 8")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_Deviation_M1.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Bands_Period_M1
  Bands_Period_M5:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M5
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SET_PARAMS: Bands_Period_M5
      SETFILE: /opt/sets/EA31337-Bands_Period_M5.set
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 2 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 2 * 8"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 2 * 8")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_Deviation_M5.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Bands_Period_M5
  Bands_Period_M15:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M15
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SET_PARAMS: Bands_Period_M15
      SETFILE: /opt/sets/EA31337-Bands_Period_M15.set
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 2 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 2 * 8"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 2 * 8")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_Deviation_M15.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Bands_Period_M15
  Bands_Period_M30:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      BT_PERIOD: M30
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SET_PARAMS: Bands_Period_M30
      SETFILE: /opt/sets/EA31337-Bands_Period_M30.set
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 2 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 2 * 4"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 2 * 4")
        2
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_Deviation_M30.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Bands_Period_M30
  Bands_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_Applied_Price
      RUN_ON_SET: set_opt_params Bands_Applied_Price 0 6
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Deviation_M1.set
        /opt/sets/EA31337-Bands_Deviation_M15.set
        /opt/sets/EA31337-Bands_Deviation_M30.set
        /opt/sets/EA31337-Bands_Deviation_M5.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Period_M1.set
        /opt/sets/EA31337-Bands_Period_M15.set
        /opt/sets/EA31337-Bands_Period_M30.set
        /opt/sets/EA31337-Bands_Period_M5.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_Applied_Price.set
      TEST_REPORT_NAME: EA31337-Bands_Applied_Price
  Bands_HShift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_HShift
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 1 * 2"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 1 * 2")
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_Deviation_M1.set
        /opt/sets/EA31337-Bands_Deviation_M15.set
        /opt/sets/EA31337-Bands_Deviation_M30.set
        /opt/sets/EA31337-Bands_Deviation_M5.set
        /opt/sets/EA31337-Bands_Period_M1.set
        /opt/sets/EA31337-Bands_Period_M15.set
        /opt/sets/EA31337-Bands_Period_M30.set
        /opt/sets/EA31337-Bands_Period_M5.set
        /opt/sets/EA31337-Bands_Shift.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_HShift.set
      TEST_REPORT_NAME: EA31337-Bands_HShift
  Bands_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_SignalLevel
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(bc <<< "$$(input_get $${SET_PARAMS}) - 0.1 * 5")
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 0.1 * 5")
        0.1
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_Deviation_M1.set
        /opt/sets/EA31337-Bands_Deviation_M15.set
        /opt/sets/EA31337-Bands_Deviation_M30.set
        /opt/sets/EA31337-Bands_Deviation_M5.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Period_M1.set
        /opt/sets/EA31337-Bands_Period_M15.set
        /opt/sets/EA31337-Bands_Period_M30.set
        /opt/sets/EA31337-Bands_Period_M5.set
        /opt/sets/EA31337-Bands_Shift.set
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Bands_SignalLevel
  Bands_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2019-DS
    volumes:
      - ./sets/EURUSD:/opt/sets:rw
      - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 6-12
      SET_PARAMS: Bands_Shift
      RUN_ON_SET: >
        set_opt_params $${SET_PARAMS}
        $$(get_max 0 $$(bc <<< "$$(input_get $${SET_PARAMS}) - 1 * 2"))
        $$(bc <<< "$$(input_get $${SET_PARAMS}) + 1 * 2")
      RUN_ON_SUCCESS: >
        input_copy "$${SET_PARAMS}" "$${SETFILE}"
        /opt/sets/EA31337-Bands_Applied_Price.set
        /opt/sets/EA31337-Bands_Deviation_M1.set
        /opt/sets/EA31337-Bands_Deviation_M15.set
        /opt/sets/EA31337-Bands_Deviation_M30.set
        /opt/sets/EA31337-Bands_Deviation_M5.set
        /opt/sets/EA31337-Bands_HShift.set
        /opt/sets/EA31337-Bands_Period_M1.set
        /opt/sets/EA31337-Bands_Period_M15.set
        /opt/sets/EA31337-Bands_Period_M30.set
        /opt/sets/EA31337-Bands_Period_M5.set
        /opt/sets/EA31337-Bands_SignalLevel.set
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      SETFILE: /opt/sets/EA31337-Bands_Shift.set
      TEST_REPORT_NAME: EA31337-Bands_Shift
