version: '3.4'
services:
  Bands_Period:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands_Period
      RUN_ON_SET: set_opt_params Bands_Period $$(bc <<< "$$(input_get Bands_Period) - 2 * 4") $$(bc <<< "$$(input_get Bands_Period) + 2 * 4") 2
      SETFILE: /opt/sets/EA31337-Bands_Period.set
      TEST_REPORT_NAME: EA31337-Bands_Period
    deploy:
      restart_policy:
        condition: none
  Bands_Applied_Price:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands_Applied_Price
      RUN_ON_SET: set_opt_params Bands_Applied_Price 0 6
      SETFILE: /opt/sets/EA31337-Bands_Applied_Price.set
      TEST_REPORT_NAME: EA31337-Bands_Applied_Price
    deploy:
      restart_policy:
        condition: none
  Bands_Deviation:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands_Deviation
      RUN_ON_SET: set_opt_params Bands_Deviation $$(bc <<< "$$(input_get Bands_Deviation) - 0.1 * 5") $$(bc <<< "$$(input_get Bands_Deviation) + 0.1 * 5") 0.1
      SETFILE: /opt/sets/EA31337-Bands_Deviation.set
      TEST_REPORT_NAME: EA31337-Bands_Deviation
  Bands_SignalLevel:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SET_PARAMS: Bands_SignalLevel
      RUN_ON_SET: set_opt_params Bands_SignalLevel $$(bc <<< "$$(input_get Bands_SignalLevel) - 0.1 * 5") $$(bc <<< "$$(input_get Bands_SignalLevel) + 0.1 * 5") 0.1
      SETFILE: /opt/sets/EA31337-Bands_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Bands_SignalLevel
    deploy:
      restart_policy:
        condition: none
  Bands_Shift:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets/EURUSD:/opt/sets:rw
    - ./_results/EURUSD:/opt/_results:rw
    environment:
      SET_PARAMS: Bands_Shift
      RUN_ON_SET: set_opt_params Bands_Shift $$(bc <<< "$$(input_get Bands_Shift) - 1 * 2") $$(bc <<< "$$(input_get Bands_Shift) + 1 * 2")
      SETFILE: /opt/sets/EA31337-Bands_Shift.set
      TEST_REPORT_NAME: EA31337-Bands_Shift
    deploy:
      restart_policy:
        condition: none
